package com.umeng.soexample.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.umeng.soexample.model.ShopsBean;
import com.umeng.soexample.model.ShopsJsonBean;

import com.umeng.soexample.greendao.ShopsBeanDao;
import com.umeng.soexample.greendao.ShopsJsonBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopsBeanDaoConfig;
    private final DaoConfig shopsJsonBeanDaoConfig;

    private final ShopsBeanDao shopsBeanDao;
    private final ShopsJsonBeanDao shopsJsonBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopsBeanDaoConfig = daoConfigMap.get(ShopsBeanDao.class).clone();
        shopsBeanDaoConfig.initIdentityScope(type);

        shopsJsonBeanDaoConfig = daoConfigMap.get(ShopsJsonBeanDao.class).clone();
        shopsJsonBeanDaoConfig.initIdentityScope(type);

        shopsBeanDao = new ShopsBeanDao(shopsBeanDaoConfig, this);
        shopsJsonBeanDao = new ShopsJsonBeanDao(shopsJsonBeanDaoConfig, this);

        registerDao(ShopsBean.class, shopsBeanDao);
        registerDao(ShopsJsonBean.class, shopsJsonBeanDao);
    }
    
    public void clear() {
        shopsBeanDaoConfig.clearIdentityScope();
        shopsJsonBeanDaoConfig.clearIdentityScope();
    }

    public ShopsBeanDao getShopsBeanDao() {
        return shopsBeanDao;
    }

    public ShopsJsonBeanDao getShopsJsonBeanDao() {
        return shopsJsonBeanDao;
    }

}
